// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Prueba01","status":false,"description":"","parameters":{"nombre":"Dálibor","edad":"21","historial":"Hijo del herrero de Bólidior."}},
{"name":"ShowConsoleOnBoot","status":false,"description":"Shows the developer console on boot.","parameters":{"Console Width":"800","Console Height":"300","Console X-Position":"0","Console Y-Position":"0","Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}},
{"name":"Prueba02","status":false,"description":"","parameters":{}},
{"name":"Prueba03","status":false,"description":"","parameters":{}},
{"name":"Prueba04","status":false,"description":"","parameters":{}},
{"name":"Prueba05","status":false,"description":"","parameters":{"imagen":"destellos"}},
{"name":"Prueba06","status":false,"description":"","parameters":{}},
{"name":"Prueba07_GO","status":true,"description":"","parameters":{"ImagenFinal":"final","SonidoFinal":"final"}},
{"name":"Prueba08","status":true,"description":"","parameters":{}},
{"name":"Prueba09","status":true,"description":"","parameters":{}}
];
